#!/bin/bash

LATEST_VERSION=$(curl -s https://go.dev/VERSION?m=text | head -n 1)
LATEST_VERSION=${LATEST_VERSION#go}
INSTALL_DIR="/usr/local"

wget "https://go.dev/dl/go${LATEST_VERSION}.linux-amd64.tar.gz"

rm -rf /usr/local/go && tar -C /usr/local -xzf go${LATEST_VERSION}.linux-amd64.tar.gz
